name: Run NourishAI Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-my-container:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull carlamine/nourishai-app:latest

      - name: Run container (smoke test)
        run: |
          docker run --rm --name nourishai-test carlamine/nourishai-app:latest
